Delete diary features
MemoMood/MemoMood pull request #51
Opened 2022-11-22 18:47 UTC by panitnt

2022-11-22 19:58 UTC, natekrth requested changes
Cannot delete my diary

2022-11-22 22:51 UTC, teenteennnii approved these changes
Good

2022-11-23 01:49 UTC, sivazzer approved these changes
Approved.

2022-11-23 02:54 UTC, natekrth approved these changes
Great. Thank you

2022-11-23 02:55 UTC, merged